import type { Metadata } from 'next'
import Link from 'next/link'
import { buildMetadata } from '@/lib/seo'
import Breadcrumb from '@/components/Breadcrumb'
import RelatedPages from '@/components/RelatedPages'
import SideRailAds from '@/components/SideRailAds'
import TokenToUsdClient from './TokenToUsdClient'
import JsonLd, { webAppSchema, howToSchema, breadcrumbSchema } from '@/components/JsonLd'

export const metadata: Metadata = buildMetadata({
  title: 'Token to USD Calculator — Convert AI Tokens to Dollars',
  description:
    'Enter any token count and see the exact USD cost for Claude, GPT-4o, Gemini, and more. Free AI token to dollar converter with live pricing.',
  path: '/tools/token-to-usd',
})

const RELATED = [
  { href: '/tools/words-to-tokens', label: 'Words → Tokens Converter', description: 'Paste text to estimate its token count.' },
  { href: '/', label: 'Full Token Calculator', description: 'Convert money, tokens, or characters across all models.' },
  { href: '/compare/cheapest-ai-models', label: 'Cheapest AI Models 2026', description: 'Ranked by input token price.' },
  { href: '/blog/fundamentals/how-ai-api-pricing-works', label: 'How AI Pricing Works', description: 'Understand the per-token billing model.' },
]

const HOW_TO_STEPS = [
  {
    name: 'Enter a token count',
    text: 'Type the number of tokens you want to price. The calculator starts at 1,000,000 tokens so you see live figures instantly.',
  },
  {
    name: 'Find your model',
    text: 'Search by name — like Sonnet, GPT-4o, or Gemini — or tap a provider to narrow the list. Sort by clicking any column header.',
  },
  {
    name: 'Read input and output cost',
    text: 'Each model shows its exact USD cost for input tokens (sent to the model) and output tokens (generated by it) side by side. Output is typically 3–5× more expensive.',
  },
]

export default function TokenToUsdPage() {
  return (
    <>
      <JsonLd data={webAppSchema()} />
      <JsonLd
        data={howToSchema({
          name: 'How to convert AI tokens to USD',
          description:
            'Convert any AI token count to its exact dollar cost across Claude, GPT-4o, Gemini, and other major models.',
          url: 'https://tokenrate.dev/tools/token-to-usd',
          totalTime: 'PT30S',
          steps: HOW_TO_STEPS,
        })}
      />
      <JsonLd
        data={breadcrumbSchema([
          { name: 'TokenRate', url: 'https://tokenrate.dev' },
          { name: 'Tools', url: 'https://tokenrate.dev/tools/token-to-usd' },
          { name: 'Token to USD', url: 'https://tokenrate.dev/tools/token-to-usd' },
        ])}
      />

      {/* House ads — Nodea rails in the empty page margins (labelled advertising).
          Placed here because this is the site's #1 traffic page. */}
      <SideRailAds />

      <div className="mx-auto max-w-3xl px-6 py-10">
      <Breadcrumb crumbs={[{ label: 'Home', href: '/' }, { label: 'Tools' }, { label: 'Token → USD' }]} />

      <div className="mb-8">
        <h1 className="text-3xl font-bold text-zinc-900 dark:text-zinc-50 mb-2">
          Token to USD Calculator
        </h1>
        <p className="text-zinc-500 dark:text-zinc-400 text-sm">
          Enter a token count to see the exact dollar cost across major AI models — for both input and output pricing.
        </p>
      </div>

      <TokenToUsdClient />

      {/* Funnel the site's #1 entry page into the fuller calculator. This page ranks
          because it's lean; the CTA converts that traffic to money/character input,
          quality scores, value ranking, and compare mode without bloating the tool. */}
      <Link
        href="/"
        className="group mt-8 flex items-center gap-4 rounded-xl border border-emerald-200 dark:border-emerald-900/60 bg-emerald-50/60 dark:bg-emerald-950/20 p-5 hover:border-emerald-400 dark:hover:border-emerald-700 hover:shadow-sm transition-all"
      >
        <div className="flex-1">
          <p className="text-sm font-semibold text-zinc-900 dark:text-zinc-50">
            Compare quality and value, not just cost
          </p>
          <p className="mt-1 text-xs leading-relaxed text-zinc-500 dark:text-zinc-400">
            The full calculator adds dollar &amp; character input, quality scores, value-per-dollar
            ranking, and side-by-side model compare — across every tracked model.
          </p>
        </div>
        <span className="flex shrink-0 items-center gap-1.5 text-sm font-semibold text-emerald-700 dark:text-emerald-400">
          Open
          <svg width="16" height="16" viewBox="0 0 16 16" fill="none" className="transition-transform group-hover:translate-x-0.5">
            <path d="M3 8h10M9 4l4 4-4 4" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" />
          </svg>
        </span>
      </Link>

      <div className="mt-12">
        <RelatedPages pages={RELATED} title="Related Tools" />
      </div>
    </div>
    </>
  )
}
